name = "Reversi"
uuid = "8f7655e2-04a7-45c2-9cb3-16b1b80822ae"
version = "0.2.2"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]

[compat]
julia = "1.6, 2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]