name = "Reversi"
uuid = "8f7655e2-04a7-45c2-9cb3-16b1b80822ae"
version = "0.1.0"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6, 2"
StaticArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]